apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-frontend
  labels:
    app: ems-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-frontend
  template:
    metadata:
      labels:
        app: ems-frontend
    spec:
      containers:
      - name: ems-frontend
        image: <your_dockerhub_username>/ems-frontend:1.0
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: ems-config
