apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ems-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ems.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ems-frontend
            port:
              number: 80
